# Generated by Django 3.1.1 on 2020-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200919_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='profile_bio',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
